### ISSUE TITLE
git Wiki나 git Book을 이용하면 좋지 않을까요?

### ISSUE THREAD

**Issue by Astoration** [yoo2001818/unityLesson#1]
md파일들은 있는데 원본 프로젝트 자체나 커밋 기록은 없는데 원본 프로젝트 파일을 레슨별로 커밋하여 기록한후 git wiki나 git book을 사용하며 강의를 게재하면 좋을것 같습니다 :)

**Comment by yoo2001818** [comment]
그래도 좋을 것 같긴 한데 원본 프로젝트가 이미 덮어 씌워져버려서 복구할 방법이 없네요.

근데 원래 레포지터리를 프로젝트 파일이 아닌 레슨 문서 파일을 보관하기 위해서 만든거라 굳이 그렇게 할 필요는 없을 것 같아요.
